In [3]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
list_1= [50,60,80,100,200,300,500,600]
list_1


[50, 60, 80, 100, 200, 300, 500, 600]

In [3]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL NUMPY ARRAYS

In [4]:
type(my_numpy_array)

numpy.ndarray

In [5]:
# Multi-dimensional (Matrix definition) 
my_matrix= np.array([[2,8,8], [7,3,6]])
my_matrix

array([[2, 8, 8],
       [7, 3, 6]])

In [4]:
#0-d array with value 42
arr = np.array(42)
arr

array(42)

In [8]:
#3-D array 
arr=np.array([
    [[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]
    ])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
#check the dimension of numbers
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
##Array Indexing
arr=np.array([1,2,3,4])
arr[2]+arr[3]

##Access 3-D array
vrr= np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]]
])
vrr[1,1,1]

np.int64(11)

In [16]:
#Negative indexing to access an array from the end
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[1,-1]

np.int64(10)

In [22]:
#Array Slicing
arr= np.array([1,2,3,4,5,6,7])
arr[1:6]


array([2, 3, 4, 5, 6])

In [28]:
arr=np.array([1,2,3,4,5,6,7])
arr[5:]
arr[:4]

array([1, 2, 3, 4])

In [31]:
# Negative Slicing==>index 3 from end to index from the end
arr= np.array([1,2,3,4,5,6,7])
arr[-3:-1]

array([5, 6])

In [5]:
#Step => use the step value to determine the step of the slicing
arr= np.array([1,2,3,4,5,6,7])
arr[0:6:2]

array([1, 3, 5])

In [7]:
#Slicing 2-D Arrays
arr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[1, 1:4]

array([7, 8, 9])

In [8]:
arr=np.array([1,2,3,4], dtype='S')
arr.dtype

dtype('S1')

In [13]:
#Converting Data Type on Existing Arrays
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
newarr

array([1, 2, 3], dtype=int32)

In [ ]:
#Copy ===>> it owns the data and any change made the copy will not affect the original
arr=np.array([1,2,3,4])
x=arr.copy()
x

array([1, 2, 3, 4])

In [19]:
#view==>>does not own the data and any changes made to the view will affect the original array and change in original array will affect the view
arr=np.array([1,2,3,4])
x=arr.view()
x[0]=9
x

array([9, 2, 3, 4])

In [4]:
#shape of a 2-D array
arr= np.array([[1,2,3,4], [5,6,7,8]])

shape=arr.shape
shape

(2, 4)

In [5]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
